package rc;

/**
 *
 * @author RC_Student_lab
 */
public class Task {
    public int numOfTasks, taskStatus, taskNumber;
    public String taskName, taskDescription, devDetails, taskID;
    // missing duration
    
    public Task() {
        numOfTasks = 0;
        taskStatus = 0;
        taskNumber = 0;
        taskName = "";
        taskDescription = "";
        devDetails = "";
        taskID = "";
    }
    
    // display welcome message
    // user chooses option (1, 2 or 3)
    // user enters info
    
    // methods:
    // checkTaskDescription
    // createTaskID()
    
    // PringTaskDetails
    // returnTotalHours
    
    // my methods:
    // maybe, displayWelcome()
    // store user
    // createTask(tName, desc, devDeets, taskId)
    // the relevant attributes are assigned
    // user input is used for assigned
    // wrap createTask() in a for loop in Main. The condition being the numOfTasks
    // 
   
    public void start() {
        //
    }

    public String createTaskID(){
        // takes taskName (first 2 letters), taskNumber (autogenerated), devDetails (last 3 letters)
        // the format is tN:07:dev - "task name":taskNumber:"dev first name"
        
        // String method to extract characters in a string (first 2 letters)
        String tName = taskName.substring(0, 2);
        int tNumber = taskNumber; // this variable is for the actual taskID string
        
        String[] firstName = devDetails.split(" ");
        int lastLetter = firstName[0].length();
        int thirdLastLetter = firstName[0].length() - 3;
        String devDeets = firstName[0].substring(thirdLastLetter, lastLetter);
        
        String taskId = tName + ":" + tNumber + ":" + devDeets;
        return taskId;
    }

}
